### ISSUE TITLE
以下的代码报错了

### ISSUE THREAD

**Issue by DR-Univer** [AntoniotheFuture/ExcelFomulaBeautifier#3]
=IF(P22="","",IF(P22=Q22,0,IF(Q22>0,IF(P22>0,(Q22-P22)/P22,-(Q22-P22)/P22),IF(P22>0,-(P22-Q22)/P22,-(Q22-P22)/P22))))

**Comment by al96169** [comment]
请问是你使用我的代码构建的页面测试还是在io页面测试的呢？我访问不了io页面了，但我在我自己官网上的页面测试是通过的：
[https://tools.mindzpoint.com/excelformula](https://tools.mindzpoint.com/excelformula)
（除了有一点排版错误外）
![image](https://user-images.githubusercontent.com/34180899/91289062-5ee69f00-e7c4-11ea-99c7-89c43bb45f90.png)
![image](https://user-images.githubusercontent.com/34180899/91289085-6ad26100-e7c4-11ea-8bcc-f048e4682bd7.png)
如果是您使用我的代码构建的页面，请检查一下构建的过程 ：）

**Comment by DR-Univer** [comment]
谢谢，昨天不知道为啥不行，现在可以了
