### ISSUE TITLE
[bug]对ROUNDDOWN解析错误

### ISSUE THREAD

**Issue by godefy** [AntoniotheFuture/ExcelFomulaBeautifier#6]
=ROUNDDOWN($D4/100,0)
报错：
103:Invalid comma,无效的逗号::$D4/100,

**Comment by godefy** [comment]
=INDEX($D:$D,MATCH($R4,$D:$D,0))
这样也不行

**Comment by al96169** [comment]
已在最新的提交中修复此BUG

**Comment by godefy** [comment]
谢谢。
我刚才试了一下，这个很长的公式也解析不出来，能否再看一下是否哪里出了问题？
=@IF($R4=IFERROR(INDEX($D:$D,MATCH($R4,$D:$D,0)),0),INDEX($A:$A,MATCH($R4,$D:$D,0)+1),IFERROR((@INDEX($B:$B,IFERROR(MATCH($R4,$D:$D,1),1)+1)-IFERROR(INDEX($B:$B,MATCH($R4,$D:$D,1)),0))/@INDEX($E:$E,IFERROR(MATCH($R4,$D:$D,1),1)+1)+$T3,1))

**Comment by al96169** [comment]
> 谢谢。 我刚才试了一下，这个很长的公式也解析不出来，能否再看一下是否哪里出了问题？ =@if($R4=IFERROR(INDEX($D:$D,MATCH($R4,$D:$D,0)),0),INDEX($A:$A,MATCH($R4,$D:$D,0)+1),IFERROR((@Index($B:$B,IFERROR(MATCH($R4,$D:$D,1),1)+1)-IFERROR(INDEX($B:$B,MATCH($R4,$D:$D,1)),0))/@Index($E:$E,IFERROR(MATCH($R4,$D:$D,1),1)+1)+$T3,1))

此公式应该不是直接在Excel中复制出来的，因为他的函数名不是大写，我的程序只能识别大写的函数名，请将此公式复制到Excel的公式编辑器后再复制出来，这样我的程序才能够识别，在刚才的提交中，同时还修复了由此公式发现的另一个问题，可以使用最新的版本。

**Comment by godefy** [comment]
=@IF($R4=IFERROR(INDEX($D:$D,MATCH($R4,$D:$D,0)),0),INDEX($A:$A,MATCH($R4,$D:$D,0)+1),IFERROR((@INDEX($B:$B,IFERROR(MATCH($R4,$D:$D,1),1)+1)-IFERROR(INDEX($B:$B,MATCH($R4,$D:$D,1)),0))/@INDEX($E:$E,IFERROR(MATCH($R4,$D:$D,1),1)+1)+$T3,1))
应该是这个，我在那个网站上仍解析不出来。

**Comment by godefy** [comment]
=@IF($R4=IFERROR(INDEX($D:$D,MATCH($R4,$D:$D,0)),0),INDEX($A:$A,MATCH($R4,$D:$D,0)+1),IFERROR((@INDEX($B:$B,IFERROR(MATCH($R4,$D:$D,1),1)+1)-IFERROR(INDEX($B:$B,MATCH($R4,$D:$D,1)),0))/@INDEX($E:$E,IFERROR(MATCH($R4,$D:$D,1),1)+1)+$T3,1))
![image](https://user-images.githubusercontent.com/19462833/163986474-e39642dd-0434-4af1-819f-7330d5a024c7.png)
编辑器自动给转化的。。我试试放到代码格式里：
`=@IF($R4=IFERROR(INDEX($D:$D,MATCH($R4,$D:$D,0)),0),INDEX($A:$A,MATCH($R4,$D:$D,0)+1),IFERROR((@INDEX($B:$B,IFERROR(MATCH($R4,$D:$D,1),1)+1)-IFERROR(INDEX($B:$B,MATCH($R4,$D:$D,1)),0))/@INDEX($E:$E,IFERROR(MATCH($R4,$D:$D,1),1)+1)+$T3,1))`

**Comment by al96169** [comment]
> 

![image](https://user-images.githubusercontent.com/34180899/163990339-ea638844-d56a-468a-9ec8-caf27c6aa8e6.png)

**Comment by godefy** [comment]
可以了，谢谢~
可能我之前试的时候还没刷新缓存。
